on:
  push:
    branches:
      - "*"
      - "!main"

name: build

jobs:
  version:
    runs-on: ubuntu-24.04
    outputs:
      BUILD_BUILDNUMBER: ${{ steps.new-version.outputs.BUILD_BUILDNUMBER }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.1
          run_install: false
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          pnpm install
      - name: Build packages
        run: |
          pnpm nx run-many -t build
